### PR TITLE
Remove failure

### PR DESCRIPTION
**Pull request by PsiACE**
- switch to anyhow from failure
- fmt & clippy

### CODE REVIEW

**Comment by PsiACE** [comment]
hi @dalance , would you like to take the time to review this PR?

**Comment by dalance** [comment]
Sorry. I forgot.
I'll review this PR tomorrow.

**Comment by dalance** [comment]
How about using [thiserror](https://docs.rs/thiserror/) instead of anyhow?
In my understanding, anyhow may be for application not library.

**Comment by PsiACE** [comment]
> How about using [thiserror](https://docs.rs/thiserror/) instead of anyhow?

Using thiserror is good, but in the current situation, anyhow is enough

**Comment by dalance** [comment]
OK. I'll merge this.

**Comment by dalance** [comment]
I released v0.5.0.

**Comment by PsiACE** [comment]
> I released v0.5.0.

Thanks for your work.

**Pull request merged**
